### ISSUE TITLE
Can't cancel eth transactions that are stuck

### ISSUE THREAD

**Issue by kampaidev** [digitalbitbox/bitbox02-firmware#1070]
I have multiple eth transactions that have been stuck for days, no way to cancel them or use the wallet because of it, how can I recover my keys, or cancel these transactions?

**Comment by benma** [comment]
Hi

Please contact support@shiftcrypto.ch for support questions, or join the Telegram chat. 

Maybe this will help: 

https://shiftcrypto.support/help/en-us/36-rabby-metamask-fork/183-how-to-speed-up-an-eth-token-transaction

You can also try deleting the `cache` folder in the same location as https://shiftcrypto.support/help/en-us/15-other/101-support-files.
