### ISSUE TITLE
Anti-klepto for Ethereum and Cardano?

### ISSUE THREAD

**Issue by jcw1tjjrdhv3** [digitalbitbox/bitbox02-firmware#1107]
Does anti-klepto work with Ethereum (via MyEtherWallet) and Cardano? Sorry if this is a wrong place to ask, but I couldn't find an answer anywhere on the website. Perhaps this is something that could be added to the knowledgebase.

**Comment by benma** [comment]
It is supported for all ECDSA signatures, which means it is supported for Ethereum, also via MEW. Cardano does not use ECDSA, so there is no support for anti-klepto in Cardano. See also https://bitbox.swiss/bitbox02/threat-model/.

**Comment by jcw1tjjrdhv3** [comment]
I see, thank you. But can it also be implemented for Cardano and if yes, are there any plans to do so in the future?

**Comment by benma** [comment]
We haven't looked into if it's possible for Cardano. There are no plans for that.

**Comment by jcw1tjjrdhv3** [comment]
OK, thanks for the info.
