### ISSUE TITLE
I loss my sd-card backup, how to protect my funds?

### ISSUE THREAD

**Issue by satoshinotdead** [digitalbitbox/bitbox02-firmware#1128]
Hi there!

I loss my sd-card backup and I dont know how to protect my funds and not get exposed because the lack of encryption.

There is some guide to follow?
Thanks :)

**Comment by benma** [comment]
Hi, this is a technical issue tracker. For user support, please contact support@bitbox.swiss.

Generally, if there is a risk that another person can find your backup, you should 

- create a new backup (sdcard or write down the 24 recovery words) of your existing wallet
- create another wallet (new seed, new backup) and transfer your funds from the old wallet to your new wallet. 

Again, best to contact support@bitbox.swiss. 

Also don't respond to any unsolicited messages here or elsewhere. Never share your recovery words or type them into websites, etc.
