### ISSUE TITLE
Error: panicked at 'spawn: wrong state', src/bitbox02-rust/src/async_usb.rs:106:14

### ISSUE THREAD

**Issue by Czino** [digitalbitbox/bitbox02-firmware#1141]
A friend of mine encountered this error once using a MacBook 

`Error: panicked at 'spawn: wrong state', src/bitbox02-rust/src/async_usb.rs:106:14`

Issue resolved itself right after.

**Comment by thisconnect** [comment]
@Czino  could you provide steps to reproduce?

**Comment by benma** [comment]
There is not much to do here in the firmware code - I assume it happened due to a communication glitch (not properly connected USB, wobbly, maybe bad adapter/cable). 

@Czino if it happens repeatedly, you or your friend should reach out to support@bitbox.swiss.
