### ISSUE TITLE
Impact of GHSA-wj6h-64fc-37mp on Python Bitbox package

### ISSUE THREAD

**Issue by dspicher** [digitalbitbox/bitbox02-firmware#1168]
A timing attack [has been published](https://github.com/advisories/GHSA-wj6h-64fc-37mp) for signatures created with the `ecdsa` package on the P-256 curve.

As far as I can tell (grepping for `NIST256p`), P-256 usage in the `bitbox02` package is restricted to verifying signatures. I would therefore conclude that the `bitbox02` package is not affected by the vulnerability. Do you agree?

**Comment by benma** [comment]
Thanks! Yes, I agree.

**Comment by dspicher** [comment]
Great, thanks for the quick response.
