### ISSUE TITLE
Feature request: add extended ascii caracters for password input

### ISSUE THREAD

**Issue by wilya7** [digitalbitbox/bitbox02-firmware#151]
Hello, I wanted to use bitbox02 as a second device to use in case of emergency with the same BIP39 seeds of an other wallet, however since I have a 25th word containing ascii extended characters (such as !@#$%^&*(){}:;"'.,?/\ ..) I could not do that. Would be possible to add these characters to the firmware?

**Comment by benma** [comment]
Hi @wilya7 

Thanks for the request. This is definitely a useful feature. I'm working on adding it.

**Comment by benma** [comment]
Support added in https://github.com/digitalbitbox/bitbox02-firmware/pull/154. This will be available with the next firmware update.

The initial set of supported special characters will be the space ` ` plus `!"#$%&'()*+,-./:;<=>?^[\]@_{|}`, which is nearly all of them.

I hope this helps. Please re-open the issue if needed.

**Comment by benma** [comment]
Fyi, the feature is now released in firmware v4.2.1, which can be installed with the [BitBoxApp](https://shiftcrypto.ch/start/).
