### ISSUE TITLE
[Feature request] openpgp keychain support

### ISSUE THREAD

**Issue by morgankevinj** [digitalbitbox/bitbox02-firmware#306]
It would be a useful feature to store PGP private keys securely on the device.
https://wiki.gnupg.org/SmartCard

**Comment by benma** [comment]
Thanks for your request. It is something the bitbox02 engineers themselves would find quite useful when signing git commits ;)

It is unfortunately not on our roadmap currently, as we have lots of features already we want to deliver.  This might change in the future, in which case you will hear about it through our release notes / tweets / emails etc.

Cheers.
