### ISSUE TITLE
Bitcoin Cash support

### ISSUE THREAD

**Issue by StEvUgnIn** [digitalbitbox/bitbox02-firmware#313]
Hi, 
Do you consider supporting Bitcoin Cash and other bitcoin forks?

Thanks a lot,
Steve

**Comment by benma** [comment]
We are continuously considering supporting more coins. Bitcoin Cash and other forks are currently not on the roadmap, though this might change in time.

**Comment by gasull** [comment]
Has this changed?

Your website says "We focus our efforts on the top tier coins under active development".

Bitcoin Cash is number 5 in market capitalization and is under active development.  You're supporting other coins with much lower market value.

**Comment by benma** [comment]
Unfortunately no change regarding Bitcoin Cash at this moment. I'll be sure to re-open this issue if this changes.
