### ISSUE TITLE
Firmware 9.0.0 requested by Electrum Wallet

### ISSUE THREAD

**Issue by csh2000** [digitalbitbox/bitbox02-firmware#526]
Hello, running Electrum Wallet AppImage 4.0.1 (just released). 

Connection to BB02 works fine, but it is asking for 9.0.0 firmware.

I have 8.0.0 installed and 9.0.0 seems not have been released yet...

Thanks!

![Electrum](https://user-images.githubusercontent.com/32745411/86509330-78342600-bde7-11ea-9b10-9061e4e8cf41.JPG)

**Comment by benma** [comment]
We will release a new BitBoxApp with the firmware v9.0.0 in the coming days, restoring compatibility.

If it's urgent, please let me know, and we will figure out something quicker.

**Comment by csh2000** [comment]
No problem, can wait.

Thanks!

**Comment by benma** [comment]
The upgrade is out now, see the [blog post](https://medium.com/shiftcrypto/bitbox-07-2020-lidernen-update-493f670860aa) and the [app](https://shiftcrypto.ch/download/).

**Comment by csh2000** [comment]
Hi, upgraded BitBox02  to 9.0 and worked fine with Electrum AppImage 4.0.2 in Linux Ubuntu 18.04.4 LTS.

Good point is that now I can use other "derivation paths", not only 84´/0´/0´!!

I think this could be included in BitBoxApp too.

Thanks!

**Comment by benma** [comment]
You can vary only the last part, the account index, up to 100 accounts. The previous elements of the keypath are restricted, as a security measure.

> I think this could be included in BitBoxApp too.

Working on it :nerd_face:
