### ISSUE TITLE
[Feature request] Restore from seed

### ISSUE THREAD

**Issue by reardencode** [digitalbitbox/bitbox02-firmware#68]
Reading through the code and README here it doesn't look like the bitbox02 supports restoring from a seed other than through the SD card. Would be nice to be able to round-trip a physical (written, engraved, stamped, etc.) seed.

Bonus points for checking (probably with a warning, not failure) the BIP39 checksum.

**Comment by benma** [comment]
Hi @reardencode 

This feature is actually work in progress right now and will be released pretty soon. See https://github.com/digitalbitbox/bitbox02-firmware/pull/70. Same as exporting the mnemonic phrase. 

We will however enforce the checksum and support the standard English wordlist only.

**Comment by reardencode** [comment]
BIP39 specifies that an invalid checksum should result in warning:

> Although using a mnemonic not generated by the algorithm described in "Generating the mnemonic" section is possible, this is not advised and software must compute a checksum for the mnemonic sentence using a wordlist and issue a warning if it is invalid. 

--Brandon, sent by an android

-----Original Message-----

**Comment by benma** [comment]
Yes, we are aware. We chose to support only a subset of bip39 for the time being with the English wordlist and the checksum, as this allows to convert the phrase back to the original entropy.

**Comment by reardencode** [comment]
Gotcha. Thanks! Can't wait to buy bitbox02! Looks amazing :)

--Brandon, sent by an android

-----Original Message-----

**Comment by benma** [comment]
Thanks :heart:

**Comment by benma** [comment]
Merged https://github.com/digitalbitbox/bitbox02-firmware/pull/70, with the release coming soon.
