### ISSUE TITLE
Housing specs

### ISSUE THREAD

**Issue by unixb0y** [digitalbitbox/bitbox02-firmware#701]
Would it be possible to get exact housing dimensions to design 3D-printable cases for the BitBox02?

**Comment by x1ddos** [comment]
@jadzeidan should be able to produce more precise metrics compared to https://shiftcrypto.ch/bitbox02/#specifications.

**Comment by unixb0y** [comment]
thanks!

**Comment by jadzeidan** [comment]
@unixb0y Here are dimensions of the PCB and the location of the OLED with respect to it:

![image](https://user-images.githubusercontent.com/42831937/105647259-a4f37c00-5ea4-11eb-99d8-5072dec93a07.png)
![image](https://user-images.githubusercontent.com/42831937/105647280-bf2d5a00-5ea4-11eb-8426-ae3a2ce145b2.png)
![image](https://user-images.githubusercontent.com/42831937/105647255-9e650480-5ea4-11eb-9fed-751713a847ae.png)

**Comment by unixb0y** [comment]
@jadzeidan Thanks a lot!
