### ISSUE TITLE
Signing a message with a Bitcoin address?

### ISSUE THREAD

**Issue by lf94** [digitalbitbox/bitbox02-firmware#727]
Is there any support for signing a message with a Bitcoin address? If not, what's the rationale?

**Comment by benma** [comment]
It is supported. You can sign messages using Electrum (right click an address, sign).

See also: https://shiftcrypto.ch/blog/bitbox02-with-electrum-wallet/

**Comment by lf94** [comment]
Thank you for the reply @benma :slightly_smiling_face: 

I asked because it appears bitbox02-api-js doesn't expose this functionality (https://github.com/digitalbitbox/bitbox02-api-js/issues/35). At the very least, at least it appears I can add support since the underlying firmware supports it.

**Comment by x1ddos** [comment]
@lf94 JS API does support it. Let's continue in that issue.
