### ISSUE TITLE
Error: panicked at after unlocking

### ISSUE THREAD

**Issue by voyager-dotnet** [digitalbitbox/bitbox02-firmware#746]
Hey,

I setup my new bitbox. After setting it up, I unplugged and replugged it.
I entered the password to unlock the device and got the following error:

```
Error: panicked at `keystore unlock failed`, src/bitbox02-rust/src/workflow/unlock.rs:87:14`
```

![bitbox-error](https://user-images.githubusercontent.com/83450320/116679294-a7d1a180-a9aa-11eb-8da5-46e24531d23a.jpg)

After I unplugged and tried again, it worked. Could not reproduce it a 2nd time.
Do I have to be worried? Any idea why this happened?

**Comment by thisconnect** [comment]
I believe this happened to me too on an Android with wonky usb-c connection when the device power got interrupted.

**Comment by benma** [comment]
Thanks for the report @voyager-dotnet . Does it happen everytime you unlock, or was it only one time?

**Comment by benma** [comment]
Adding more information to this error message so can have more to go on if it happens again: https://github.com/digitalbitbox/bitbox02-firmware/pull/757

**Comment by benma** [comment]
We have improved the communication to the securechip by switching to polling instead of using timings. Closing as there is nothing more to do for now.
