### ISSUE TITLE
Feature: WalletMatrix Support

### ISSUE THREAD

**Issue by dcentrica** [digitalbitbox/bitbox02-firmware#791]
Adds an informational meta-file about Bitbox02's features to its public GitHub repo for auto-import into [WalletMatrix](https://walletmatrix.app).

WalletMatrix is a Bitcoin wallet feature discovery tool for folks to find wallets by feature, language and platform alongside contextual help content, a [developer API](https://walletmatrix.app/developers) and heaps more. There are several similar services which rely on manual and centralised data curation, but since wallet projects iterate so quickly, WalletMatrix automates an otherwise unsustainable update process.

Merging this PR exposes Bitbox02's features via a standard [`matrix.json`](https://walletmatrix.app/schema) file which allows WalletMatrix to automatically parse, consume and store Bitbox02's features, making them available to search almost immediately.

**What do I need to do?**

 1. Merge an incoming PR (feel free to comment on it first!)
 2. Keep your new `matrix.json` up-to-date :-)

**Resources**

* [The Matrix Itself](https://walletmatrix.app/matrix/)
* [The Glossary](https://walletmatrix.app/glossary)
* [About WalletMatrix](https://walletmatrix.app/about/)
* `matrix.json` is currently based on our [v3 JSON schema](https://walletmatrix.app/schema/v3.json)
* See [an example `matrix.json` file here](https://github.com/dcentrica/walletmatrix-acme-wallet)
* Need a UUID for a new wallet? Just call our [`uuid`](https://walletmatrix.app/api/v1/uuid) API
* [Wallet Vendor Info](https://walletmatrix.app/vendors/)

**Questions?**

* [FAQ](https://walletmatrix.app/faq/)
* [Vendor Info](https://walletmatrix.app/vendors/)
* [Twitter](https://twitter.com/walletmatrix)
* Email: hello AT dcentrica DOT com

**Comment by benma** [comment]
We won't add a this meta-file for the time being, as it's another thing in a long list of things we'd have to maintain. 

Judging by the https://twitter.com/walletmatrix WalletMatrix seems to be quite inactive. We encourage you to re-open the issue and PR you opened once walletmatrix grows in usage and our effort is justified. Thanks for your understanding.
