### ISSUE TITLE
Make Opensea transactions work

### ISSUE THREAD

**Issue by benma** [digitalbitbox/bitbox02-firmware#843]
The size of the contract data in Opensea transactions is larger than the BitBox02 accepts, leading to an 'Invalid Input' error.

The size limit should be increased to accommodate opensea transactions.

Ideally, Opensea transactions would be parsed and displayed in a human readable format instead. The current way to display the raw contract data is only safe for expert users that know how to verify it, but that is not feasible for huge contract data fields like with Opensea.

**Comment by EVLRBT-01** [comment]
Thanks for this. Would EIP-712 support help in parsing the contract data?

Discussions at https://github.com/trezor/trezor-firmware/pull/1568 and https://github.com/LedgerHQ/app-ethereum/issues/105 might provide some useful context.

**Comment by benma** [comment]
EIP712 seems to be a message signing format. I am not sure if Opensea uses this, but this issue is about parsing the contract data field in a transaction to the opensea contract, which is onchain - message signing is independent of that I think.

**Comment by EVLRBT-01** [comment]
Hmmm, does the whole contract get passed to the device for signing? My naive thought was that it sent the message for signing, which has a JSON payload of all the relevant info to be shown on the device.

Perhaps not the issue as you suggest, but may be useful nonetheless.

**Comment by benma** [comment]
For an onchain transaction, the contract data is inside the transaction, and the whole transaction is sent to the device for signing. This would happen e.g. when you buy an NFT I think.

There are other operations that require message signing (EIP712), e.g. listing a new NFT.

**Comment by remixie** [comment]
@x1ddos @benma  Don't set this ticket as an "enhancement". There is a lot of people right now mad that their trezor wallets have Opensea NFTs held hostage due to lack of support. Ledger already has this issue resolved a while ago. Get this fixed. This is not a request. Due to the time sensitive nature of tons of my NFT's, my portfolio is going to take a huge loss and there will be consequences if this happens.

**Comment by remixie** [comment]
I deleted my previously heated message. I would like however for this to be fixed in a timely manner because I am genuinely afraid that my portfolio will take a huge loss due to the time-sensitive nature of NFTs at the moment.

**Comment by x1ddos** [comment]
so, what's the max size of contract data, is it spec'ed anywhere? does [EIP-170](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md) relate to this at all?

**Comment by EVLRBT-01** [comment]
I'm not sure if this should work, but tried a similar action on the Polygon network using Rabby and got as far as submitting a transaction to unlock selling via OpenSea. The sign transaction dialog pops up, I click Sign and then nothing appears on the BB02 (no errors on console). 

Having said that, trying to send MATIC on Polygon had same result, which is surprising as it is an ERC20 token. I figured it would just be the difference in testnet/mainnet.

**Comment by benma** [comment]
@EVLRBT-01 the polygon network is not supported by the BitBox02.
