### ISSUE TITLE
Stop screensaver while on tx send/receive screens

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox02-firmware#856]
for example:

1. start a new send transaction in the app.
2. bb02 displays the amount + fee, waiting for the use to confirm
3. wait on that screen and observe screensaver kicking in at some point

same for receiving while on the address confirmation screen.
i find it a suboptimal UX.

**Comment by benma** [comment]
What about all the other workflows that involve user input on the device?

Maybe we could also increase the time until the screensaver kicks in, from 1min to e.g. 5min or 10min?

This might improve the UX issue and also protect the screen if the device is left in this state for much longer.
