### ISSUE TITLE
Support for chainId greater than 8 bits

### ISSUE THREAD

**Issue by skenaja** [digitalbitbox/bitbox02-firmware#880]
It looks like the firmware expects the chainId to be 8 bits in length for signing transactions, i.e. max value 127. This prevents support for EVM networks like Palm Network which has a chainId = 11297108109 (so 64 bits).  There are many other networks with higher chainIds at https://chainlist.org/ including Polygon & Avalanche.

Is this a hardware limitation, or could it be supported?

**Comment by benma** [comment]
There is no hardware limitation, but we only support the ETH chain and Rinkeby/Ropsten testnet chains at the moment. cc @jadzeidan

**Comment by benma** [comment]
Support for chain ids up to 8 bytes: https://github.com/digitalbitbox/bitbox02-firmware/pull/881/

**Comment by benma** [comment]
v9.10.0 will support Binance Smart Chain, Optimism, Polygon, Fantom Opera and Arbitrum One networks.
