### ISSUE TITLE
UI inconsistency when entering password

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox02-firmware#92]
Upgraded to firmware v3.0.0 (beta device) and tried the new input method like in https://twitter.com/ShiftCryptoHQ/status/1162301973347147776. I can't always reproduce it reliably but here it is:

1. Touch drag a finger a little somewhere between the top middle and top right where the arrow down is. At the same time, also touch at the bottom right as if you were confirming the password. Character set disappears:

![IMG_20190818_225500(1)](https://user-images.githubusercontent.com/25405/63231289-c82eec00-c219-11e9-8ce2-df5e4da6c8c9.jpg)

Note that my fingers aren't touching the device at all in the photo anymore.

2. Touch again a couple times somewhere in the middle at the top. Everything reappears but the character set indicator at the top does not match the actual characters displayed at the bottom:

![IMG_20190818_225822(1)](https://user-images.githubusercontent.com/25405/63231326-5c00b800-c21a-11e9-8a11-14ab9b948a0f.jpg)
 
Feels like a race condition somewhere in the UI code.

**Comment by thisconnect** [comment]
I can reproduce this with 4.1.0 tested with 4.1.0 and can reproduce this:

> Touch drag a finger a little somewhere between the top middle and top right where the arrow down is.

![password-nosound](https://user-images.githubusercontent.com/546900/65694228-c86ea280-e075-11e9-90be-8b04216a4a31.gif)

**Comment by x1ddos** [comment]
> I can reproduce this

Thanks @thisconnect! I thought I was going crazy for a second. :)

**Comment by benma** [comment]
This PR probably fixes the inconsistency: https://github.com/digitalbitbox/bitbox02-firmware/pull/153

@thisconnect your gif shows a differnent issue though, which is that the touch release event was not reliably fired. Could you pls open a new issue for this (or should I?). Then we could close this one.

**Comment by thisconnect** [comment]
@benma sure, here you go #155

**Comment by benma** [comment]
Fixed, please re-open if the issue re-appears.
