### ISSUE TITLE
Wrong startup hash on BitBox02 Multi

### ISSUE THREAD

**Issue by Flash1232** [digitalbitbox/bitbox02-firmware#935]
After the most recent upgrade to fw v9.12.0 on a BitBox02 Multi I noticed the startup hash is `2ccfa688bb737c8f0888edd7bff772f26068630bbbee10dff64fad931e57325e` which is [stated](https://github.com/digitalbitbox/bitbox02-firmware/releases/tag/firmware-btc-only%2Fv9.12.0) as the Bitcoin-only firmware hash as opposed to the corresponding BB Multi hash. 

Any idea whether this is a mistake in the release notes?

**Comment by benma** [comment]
Indeed, the hashes for the two editions were accidentally swapped in the release notes. Fixed now. Thanks for the report!
